### ISSUE TITLE
Some colors seems to be defined in UMUI

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [SuperPat45/UltraModernUI#12]
Seems some colors are defined in UMUI and can't be defined in an own theme/skin.

The parts I have problems with have I marked red in the screenshots...

![2019-11-06 14_39_31-Installation von BleachBit](https://user-images.githubusercontent.com/11881073/68303330-ed5a2a80-00a3-11ea-9113-8272d07c55a3.jpg)

![2019-11-06 14_40_41-BleachBit Setup](https://user-images.githubusercontent.com/11881073/68303338-f21ede80-00a3-11ea-8452-7d7a6ac2d5b1.jpg)

My theme is based on the "Gray" theme...

**Comment by SuperPat45** [comment]
You need to remove the `XPStyle On` or `!define UMUI_XPSTYLE On` instructions from your script because with it, these colors can not be changed.

**Comment by Tobias-B-Besemer** [comment]
I guess I have to remove "!define /IfNDef UMUI_XPSTYLE On" from my theme file, too, right?

**Comment by SuperPat45** [comment]
yes
