### ISSUE TITLE
Make components page more usable?

### ISSUE THREAD

**Issue by asmaloney** [SuperPat45/UltraModernUI#4]
On my components page, the info that the user wants to interact with (the components) is squished by a whole bunch of wasted space:

![nsis](https://user-images.githubusercontent.com/391371/47927504-ddf53f80-de99-11e8-9908-5d89dfee943a.png)

How do I turn off the left image for a page?

Alternatively, how do I fix the layout so the components use the space better?

(I started with [this example](https://github.com/Drizin/NsisMultiUser/tree/master/Demos/UMUI_Ex_Full) from [NsisMultiUser](https://github.com/Drizin/NsisMultiUser). )

**Comment by SuperPat45** [comment]
You have some option to customize theUI according the documentationi:

To hide the left image:
`!define UMUI_NOLEFTIMAGE`

To change the component page layout, one of:
`!define MUI_COMPONENTSPAGE_SMALLDESC`
`!define MUI_COMPONENTSPAGE_NODESC`
`!define UMUI_COMPONENTSPAGE_BIGDESC`

You also can create your own UI by coping and editing the resource executable:

> NSIS\Contrib\UIs\UltraModernUI\UltraModern.exe

with a tool like [Resource Hacker](http://www.angusj.com/resourcehacker/).
You can remove or change position of all components of "standard" NSIS pages.

Finally, define MUI_UI to point to your edited version with this declaration to your script:
`!define MUI_UI "MyUMUI.exe"`

If you need more support, ask to the [NSIS forum](http://forums.winamp.com/forumdisplay.php?s=&forumid=65)

**Comment by asmaloney** [comment]
Ah - I didn't see `UMUI_NOLEFTIMAGE` because it wasn't next to `UMUI_UNLEFTIMAGE_BMP` in the docs :-) That just turns it off for the whole thing - not one page - and it doesn't fix the squished layout.

I thought I'd tried the other options you mention, but I guess I had them defined too late in the script. Once I move them up they have an effect. I can make do with `UMUI_COMPONENTSPAGE_BIGDESC` instead of adding more things for me to maintain by hacking the exe :-)

Merci pour l'aide!
