### ISSUE TITLE
German -> License Page -> Third line of info text is cut

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [SuperPat45/UltraModernUI#8]
In the German Translation, the info text to the license have three lines where the last line is cut.
Can you fix that in the next release?

![2019-04-17 06_41_13-Installation von BleachBit](https://user-images.githubusercontent.com/11881073/56378651-fa99ef80-620d-11e9-85a9-7e5b4ab57dd2.jpg)

**Comment by SuperPat45** [comment]
Fixed in https://github.com/SuperPat45/UltraModernUI/commit/fcf55cdf4a18f40ce3f98e314f9c822080768406

**Comment by Tobias-B-Besemer** [comment]
Thank you very much! :-)
